site_name: Perseo Context-aware Complex Event Processing
site_url: https://perseo.readthedocs.org
site_description: Perseo CEP Documentation
repo_url: https://github.com/Ficodes/perseo-fe/tree/newdocumentation
theme: readthedocs
docs_dir: documentation
site_dir: html
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_processing.css"]
#google_analytics: ['UA-84269043-1', 'wirecloud.readthedocs.io']

pages:
- 'Introduction': 'index.md'
- 'Installation & Administration Manual': 'setup.md'
- 'User Guide': 'usermanual.md'
- 'API': 'api.md'
- 'Testing': 'testing.md'
- 'Legacy documentation': 'legacy.md'

markdown_extensions:
    - markdown_github.headerid
    - markdown_github.superfences
    - markdown_github.magiclink
    - codehilite:
        guess_lang: False
    - toc:
        permalink: True
        separator: "."
