site_name: Perseo Context-aware Complex Event Processing
site_url: https://perseo.readthedocs.org
site_description: Documentation of the Perseo context-aware CEP FIWARE GE
repo_url: https://github.com/Ficodes/perseo-fe/tree/newdocumentation
theme: readthedocs
docs_dir: documentation
site_dir: html
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_processing.css"]

pages:
- 'Introduction': 'index.md'
- 'Installation & Administration Manual': 'setup.md'
- 'User & Programmers Manual': 'usermanual.md'
- 'Event, Rules and Metric APIs': 'api.md'
- 'Testing': 'testing.md'
- 'Legacy documentation':
    - 'Home': 'legacy.md' 
    - 'Architecture': 'architecture.md'
    - 'Installation & Administration Manual':
      - 'Introduction': 'admin.md'
      - 'Configuration': 'configuration.md'
      - 'Deployment': 'deployment.md'
      - 'Development': 'development.md'
      - 'Logs': 'logs.md'
    - 'User Guide':
      - 'Plain Rules': 'plain_rules.md'
      - 'Models': 'models.md'
      - 'Actions': 'pep_actions.md'
      - 'API': 'api.md'
      - 'Metrics API': 'metrics_api.md'
      - 'Errors': 'errors.md'

markdown_extensions:
    - markdown_github.headerid
    - markdown_github.superfences
    - markdown_github.magiclink
    - codehilite:
        guess_lang: True
    - toc:
        permalink: True
        separator: "."
